export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const GET_ALL_SHAPES_PENDING = 'GET_ALL_SHAPES_PENDING';
export const GET_ALL_SHAPES_SUCCESS = 'GET_ALL_SHAPES_SUCCESS';